[package]
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Drop-in serde_json replacement powered by jzon (Cargo patch)"
name = "jzon-rs-compat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default    = ["fast-float"]
simd       = ["jzon/simd"]
fast-float = ["jzon/fast-float"]
unstable   = ["jzon/unstable"]
stats      = ["jzon/stats"]

[dependencies]
jzon = { package = "jzon-rs", path = "../jzon", version = "0.3", default-features = false, features = ["compat"] }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
