[package]
name = "allocation-probe"
version = "0.0.0"
edition = "2021"
[workspace]
[dependencies]
jzon = { package = "jzon-rs", path = "../../crates/jzon", default-features = false }
jzon_serde = { package = "jzon-rs-serde", path = "../../crates/jzon_serde" }
stats_alloc = "0.1.10"
serde = "1"

[patch.crates-io]
serde_json = { path = "../../vendor/serde_json" }
